// @ts-nocheck
import { useEffect, useState } from "react";
import spotify, { getAllUserPlaylists } from "../util/spotify";
import "./Playlist.scss";
import "missing-native-js-functions";

function millisToMinutesAndSeconds(millis: number) {
	var minutes = Math.floor(millis / 60000);
	var seconds = Math.floor((millis % 60000) / 1000);
	return minutes + ":" + (seconds < 10 ? "0" : "") + seconds;
}

export default function Playlist({ id }: { id: string }) {
	const [playlist, setPlaylist] = useState<SpotifyApi.SinglePlaylistResponse | null>(null);
	const artists = new Map<string, SpotifyApi.ArtistObjectFull>();

	async function handleTracks(items: SpotifyApi.PlaylistTrackObject[]) {
		items = items.filter((x) => !!x.track.id); // filter local songs

		var artistIds = items
			.map((x) => x.track.artists.map((x) => x.id))
			.flat()
			.unique()
			// @ts-ignore
			.filter((x) => x && !artists.has(x.id));

		while (artistIds.length) {
			const batch = artistIds.slice(0, 50);
			artistIds = artistIds.slice(50);

			const { body } = await spotify.getArtists(batch);
			body.artists.forEach((x) => artists.set(x.id, x));
		}

		items.forEach(
			(x) =>
				(x.track.genres = x.track.artists
					.map((y) => artists.get(y.id)?.genres || [])
					.flat()
					.unique())
		);
		return items;
	}

	useEffect(() => {
		console.log("fetch playlist");
		spotify.getPlaylist(id, {}).then(async ({ body: state }) => {
			state.tracks.items = await handleTracks(state.tracks.items);
			setPlaylist(state);

			while (state.tracks.next) {
				console.log("fetch tracks", state.tracks);

				const { body: tracks } = await spotify.getPlaylistTracks(id, {
					offset: state.tracks.offset + state.tracks.limit,
				});

				state.tracks = { ...tracks, items: state.tracks.items.concat(await handleTracks(tracks.items)) };

				setPlaylist({ ...state });
			}
		});
	}, [id]);

	async function convert() {
		if (!playlist) return;
		// spotify
		const genres = playlist.tracks.items
			.map((x) => x.track.genres || [])
			.flat()
			.unique();

		const playlists = await getAllUserPlaylists();

		for (const genre of genres) {
			var list = playlists.items.find((x) => x.name.toLowerCase() === genre.toLowerCase());
			if (!list) {
				list = (await spotify.createPlaylist(genre, { public: false, description: `${genre} autogenerated` }))
					.body;
				playlists.items.push(list);
			}

			var songs = playlist.tracks.items
				.filter((x) => (x.track.genres || []).includes(genre))
				.map((x) => x.track.uri);

			while (songs.length) {
				const batch = songs.slice(0, 100);
				songs = songs.slice(100);

				await spotify.addTracksToPlaylist(list.id, batch, {});
			}
		}
	}

	if (!playlist) return <div>Loading playlist ...</div>;

	return (
		<div className="playlist">
			{playlist.tracks.items.length !== playlist.tracks.total && (
				<progress max={playlist.tracks.total} value={playlist.tracks.items.length}></progress>
			)}

			<div className="info">
				<div className="art">
					<img src={playlist.images.first()?.url} alt="Playlist cover" />
				</div>

				<div className="meta">
					<div className="author">{playlist.owner.display_name}</div>

					<div className="name">{playlist.name}</div>

					<div className="actions">
						<button onClick={convert} className="button-light save">
							Divide into genres
						</button>
					</div>
				</div>
			</div>

			<div className="tracks">
				<div className="heading">
					<div className="number">#</div>

					<div className="title">Song</div>

					<div className="length">Length</div>
				</div>

				{playlist.tracks.items.map((x, i) => (
					<div className="track" key={x.track.id + i + playlist.id}>
						<div className="number">{i + 1}</div>

						<div className="title">{x.track.name}</div>

						<div className="length">{millisToMinutesAndSeconds(x.track.duration_ms)}</div>
					</div>
				))}
			</div>
		</div>
	);
}
